version: "3.8"
services:
  sqlite:
    image: keinos/sqlite3:3.42.0
    volumes:
      - ./sqlite:/sqlite
    restart: always
    working_dir: /sqlite
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/mysql
      - ./mysql/data/conf.d:/etc/mysql/conf.d
    restart: always
    working_dir: /mysql
  neo4j:
    image: neo4j:5.12.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: false
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      # NEO4J_server_memory_pagecache_size: 0 # Disable page cache to not cache queries
      NEO4J_server_db_query__cache__size: 0 # Disable query cache to not cache queries - DEPRECATED
      NEO4j_server_memory_query__cache_per__db__cache__num__entries: 0 # Disable query cache to not cache queries
      # https://neo4j.com/developer/kb/understanding-transaction-and-lock-timeouts/
      NEO4J_db_transaction_timeout: 5m # Set query timeout to 5 minutes
      NEO4J_db_lock_acquisition_timeout: 5m # Set query timeout to 5 minutes
    volumes:
      - neo4j_data:/data
      - ./neo4j:/neo4j
    # NOTE: Enable for Neo4j ETL Tool MySQL link
    # links: 
    #   - mysql
    restart: always
    working_dir: /neo4j
  arangodb:
    image: arangodb:3.11.3
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1
      ARANGODB_DOCKER_TTY: true
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps
      - ./arangodb:/arangodb
      - ./arangodb/data/arangod.conf:/etc/arangodb3/arangod.conf
    restart: always
    working_dir: /arangodb
  cassandra:
    image: cassandra:4.1.3
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: ecommerce
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra:/cassandra
      - ./cassandra/data/cassandra.yaml:/etc/cassandra/cassandra.yaml
    restart: always
    working_dir: /cassandra
  mongodb:
    image: mongo:7.0.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
      - ./mongodb:/mongodb
    restart: always
    working_dir: /mongodb

volumes:
  mysql_data:
  neo4j_data:
  arangodb_data:
  arangodb_apps_data:
  cassandra_data:
  mongodb_data: