version: "3.8"
services:
  sqlite:
    image: keinos/sqlite3:3.42.0
    volumes:
      - ./sqlite/data:/data
    working_dir: /data
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    stdin_open: true
    tty: true
  neo4j:
    image: neo4j:5.12.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j_data:/data
  arangodb:
    image: arangodb:3.11.3
    ports:
      - 8529:8529
    environment:
      ARANGO_NO_AUTH: 1
      ARANGODB_DOCKER_TTY: true
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps
    stdin_open: true
    tty: true
  cassandra:
    image: cassandra:4.1.3
    ports:
      - 9042:9042
    environment:
      CASSANDRA_CLUSTER_NAME: ecommerce
    volumes:
      - cassandra_data:/var/lib/cassandra
    stdin_open: true
    tty: true
  mongodb:
    image: mongo:7.0.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    stdin_open: true
    tty: true

volumes:
  mysql_data:
  neo4j_data:
  arangodb_data:
  arangodb_apps_data:
  cassandra_data:
  mongodb_data: